services:
  tweb.production:
    container_name: tweb.production
    image: ghcr.io/iamxvbaba/gramsrv-tweb:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PRODUCTION_PORT:-80}:80"