allowBuilds:
  '@parcel/watcher@2.6.0': true
  'cpu-features@0.0.10': true
  'esbuild@0.27.4': true
  'ssh2@1.17.0': true
minimumReleaseAgeExclude:
  - 'baseline-browser-mapping@2.11.0'
  - 'browserslist@4.28.7'
  - 'electron-to-chromium@1.5.395'
  - 'oxlint@1.75.0'
  - 'oxlint-tsgolint@7.0.2001'
  - 'postcss@8.5.21'
  - 'sass@1.101.3'
  - '@oxlint-tsgolint/darwin-arm64@7.0.2001'
  - '@oxlint-tsgolint/darwin-x64@7.0.2001'
  - '@oxlint-tsgolint/linux-arm64@7.0.2001'
  - '@oxlint-tsgolint/linux-x64@7.0.2001'
  - '@oxlint-tsgolint/win32-arm64@7.0.2001'
  - '@oxlint-tsgolint/win32-x64@7.0.2001'
  - '@oxlint/binding-android-arm-eabi@1.75.0'
  - '@oxlint/binding-android-arm64@1.75.0'
  - '@oxlint/binding-darwin-arm64@1.75.0'
  - '@oxlint/binding-darwin-x64@1.75.0'
  - '@oxlint/binding-freebsd-x64@1.75.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.75.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.75.0'
  - '@oxlint/binding-linux-arm64-gnu@1.75.0'
  - '@oxlint/binding-linux-arm64-musl@1.75.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.75.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.75.0'
  - '@oxlint/binding-linux-riscv64-musl@1.75.0'
  - '@oxlint/binding-linux-s390x-gnu@1.75.0'
  - '@oxlint/binding-linux-x64-gnu@1.75.0'
  - '@oxlint/binding-linux-x64-musl@1.75.0'
  - '@oxlint/binding-openharmony-arm64@1.75.0'
  - '@oxlint/binding-win32-arm64-msvc@1.75.0'
  - '@oxlint/binding-win32-ia32-msvc@1.75.0'
  - '@oxlint/binding-win32-x64-msvc@1.75.0'
