// @ts-check
const fs = require('fs');
const path = require('path');
const emoji = require('./in/emoji_pretty.json');

const SKIN_TONE_CODE_POINTS = ['1f3fb', '1f3fc', '1f3fd', '1f3fe', '1f3ff'];
const outputPath = path.join(__dirname, '../config/emojiSkinTone.ts');

const normalizeUnified = (unified) => {
  return unified.toLowerCase().split('-').filter((codePoint) => codePoint !== 'fe0f').join('-');
};

const emojiFromCodePoints = (codePoints) => {
  return codePoints.split('-').reduce((result, codePoint) => {
    return result + String.fromCodePoint(parseInt(codePoint, 16));
  }, '');
};

const templates = {};
emoji.filter((item) => item.has_img_apple && item.skin_variations).forEach((item) => {
  const variants = Object.values(item.skin_variations);
  const variantsByTone = SKIN_TONE_CODE_POINTS.map((tone) => {
    return variants.find((variant) => {
      const tones = normalizeUnified(variant.unified)
      .split('-')
      .filter((codePoint) => SKIN_TONE_CODE_POINTS.includes(codePoint));
      return tones.length && tones.every((codePoint) => codePoint === tone);
    });
  });

  if(variantsByTone.some((variant) => !variant)) {
    return;
  }

  const baseKey = normalizeUnified(item.unified);
  templates[baseKey] = emojiFromCodePoints(normalizeUnified(variantsByTone[0].unified));
});

const entries = Object.entries(templates)
.sort(([baseA], [baseB]) => baseA.localeCompare(baseB))
.map(([base, template]) => `  '${base}': '${template}'`);

const output = `// Generated by src/scripts/generate_emoji_skin_tones.js. Do not edit manually.
const EmojiSkinToneTemplates: {[emoji: string]: string} = {
${entries.join(',\n')}
};

export default EmojiSkinToneTemplates;
`;

if(process.argv.includes('--check')) {
  if(!fs.existsSync(outputPath) || fs.readFileSync(outputPath, 'utf8') !== output) {
    console.error('Emoji skin tone config is out of date. Run pnpm generate-emoji-skin-tones.');
    process.exit(1);
  }
} else {
  fs.writeFileSync(outputPath, output);
  console.log(`Generated ${entries.length} emoji skin tone templates.`);
}
