import {z} from 'zod';
import {applyReceiptSchema} from './document-service';
import {operationsSchema} from './schemas';
import {jsonSchema,targetSchema,testRequestSchema} from './test-schemas';
import type {CompanionToolDefinition} from './transport/contracts';

const id=z.string().min(1).max(128),integer=z.number().int().min(0),strings=z.array(z.string());
const ref=z.strictObject({kind:z.enum(['bot','folder','screen','block','message','button','row','variable','table','event','case','outcome','choice']),id,parentId:id.optional()});
const outcome=z.enum(['passed','failed','blocked','observed']);
const error=z.strictObject({code:z.string(),details:jsonSchema});
export const caseResultSchema=z.strictObject({candidateHash:z.string(),testContractHash:z.string(),caseDefinitionHash:z.string(),origin:z.enum(['required_suite','ad_hoc']),caseId:id,title:z.string(),runId:id,runVersion:integer,reportId:id,outcome,complete:z.boolean(),stepsApplied:integer,attemptedStepCount:integer,resultHash:z.string(),expiresAt:integer,error:error.nullable()});
const batch=z.strictObject({operationId:id,batchId:id,candidateHash:z.string(),testContractHash:z.string(),outcome,complete:z.boolean(),cases:z.array(caseResultSchema),expiresAt:integer});
const pending=z.strictObject({operationId:id,executionStatus:z.literal('running'),complete:z.literal(false)});
const status=z.strictObject({operationId:id,executionStatus:z.string(),result:jsonSchema.optional(),error:z.string().nullable().optional()});
const failure=z.strictObject({ok:z.literal(false),error:z.strictObject({code:z.string(),message:z.string(),details:jsonSchema})});
function response(data:z.ZodType){return z.union([z.strictObject({ok:z.literal(true),data}),failure]);}
const mutationInput={botId:id,baseRevision:id,requestKey:id};
const coverageCount=z.strictObject({returned:integer,total:integer});
const prepared=z.strictObject({coverage:z.strictObject({offset:integer,nextOffset:integer.nullable(),complete:z.boolean(),collections:z.strictObject({diff:coverageCount,diagnostics:coverageCount,tests:coverageCount,idMap:coverageCount})}),changeId:id,baseRevision:id,candidateHash:z.string(),testContractHash:z.string(),state:z.enum(['ready','blocked','stale','applied']),idMap:z.record(z.string(),z.string()),
  diff:z.array(jsonSchema),diagnostics:z.array(jsonSchema),tests:z.array(caseResultSchema),missingRequiredCases:strings,reason:z.string().nullable(),expiresAt:integer,operationId:id.optional()});
const read={readOnlyHint:true,openWorldHint:false},write={readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false};
export const toolDefinitions:CompanionToolDefinition[]=[
  {name:'bot_context',description:'Current revision, actual runtime capabilities, screens, variables, explicit fixtures and required acceptance cases. Begin here; IDs are stable. Simulation never calls Telegram or providers.',inputSchema:z.strictObject({botId:id.optional()}),outputSchema:response(z.strictObject({epoch:id,botId:id,revision:id,documentHash:z.string(),capabilities:jsonSchema,counts:jsonSchema,screens:z.array(jsonSchema),variables:z.array(jsonSchema),fixtures:z.array(jsonSchema),requiredSuite:jsonSchema})),requiredScopes:['bot:read'],annotations:read},
  {name:'bot_search',description:'Find exact bot entities by text, ID or title. Returns compact hits and matching reasons; inspect before replacing incomplete content.',inputSchema:z.strictObject({botId:id,query:z.string().max(512),limit:z.number().int().min(1).max(50).default(20)}),outputSchema:response(z.strictObject({revision:id,matches:z.array(jsonSchema),coverage:z.strictObject({returned:integer,requestedLimit:integer,limited:z.boolean()})})),requiredScopes:['bot:read'],annotations:read},
  {name:'bot_inspect',description:'Inspect a full entity and references, or prepared change. Large JSON is paginated: collect every fragment before editing its full content. This never runs a bot.',inputSchema:z.strictObject({botId:id,ref:ref.optional(),changeId:id.optional(),offset:integer.default(0)}).refine(value=>!!value.ref!==!!value.changeId,'Choose ref or changeId'),outputSchema:response(z.union([prepared,z.strictObject({revision:id,contentComplete:z.boolean(),representation:z.enum(['structured','json_fragment']),content:jsonSchema,contentHash:z.string(),offset:integer,nextOffset:integer.nullable(),totalCharacters:integer})])),requiredScopes:['bot:read'],annotations:read},
  {name:'bot_prepare_change',description:'Prepare an atomic typed command batch at baseRevision, validate all Code and run ALL frozen required cases. Does not change Draft. Use $name for new entity IDs; create entities before references.',inputSchema:z.strictObject({...mutationInput,operations:operationsSchema}),outputSchema:response(z.union([prepared,pending])),requiredScopes:['bot:read','draft:write','simulation:run','simulation:read'],annotations:write},
  {name:'bot_apply_change',description:'Apply only the exact prepared candidate with complete passing required tests at the current baseRevision. Retry uncertain responses with the SAME requestKey. No force/rebase/skipTests.',inputSchema:z.strictObject({...mutationInput,changeId:id}),outputSchema:response(z.union([pending,applyReceiptSchema])),requiredScopes:['bot:read','draft:write'],annotations:write},
  {name:'bot_validate',description:'Validate structure, semantic references and all TypeScript Code for an immutable revision or candidate. This does not certify behavior or external delivery.',inputSchema:z.strictObject({botId:id,target:targetSchema}),outputSchema:response(z.strictObject({candidateHash:z.string(),valid:z.boolean(),diagnostics:z.array(jsonSchema),code:jsonSchema})),requiredScopes:['bot:read','simulation:run'],annotations:read},
  {name:'bot_test',description:'Run a frozen required suite or explicit ad hoc scenarios with /start, text, buttons, answers, virtual time, named events and manual retry. Each case has a runId. Continue one run using expectedRunVersion. Ad hoc checks never replace mandatory assertions. status/cancel use operationId.',inputSchema:testRequestSchema,outputSchema:response(z.union([batch,caseResultSchema,pending,status])),requiredScopes:['bot:read','simulation:run','simulation:read'],annotations:write},
  {name:'execution_explain',description:'Read immutable SIMULATION evidence: failed assertions, exact block IDs, actual messages, condition operands and state deltas. Paginated. No execution, retry, production history or guessed explanations.',inputSchema:z.strictObject({kind:z.literal('simulation'),reportId:id,offset:integer.default(0),limit:z.number().int().min(1).max(20).default(20),detail:z.strictObject({kind:z.enum(['assertion','receipt','observation']),index:integer,offset:integer}).optional()}),outputSchema:response(z.union([z.strictObject({reportId:id,kind:z.enum(['assertion','receipt','observation']),index:integer,offset:integer,nextOffset:integer.nullable(),totalCharacters:integer,contentHash:z.string(),representation:z.literal('json_fragment'),content:z.string()}),z.strictObject({reportId:id,runId:id,runVersion:integer,caseId:id,title:z.string(),candidateHash:z.string(),testContractHash:z.string(),caseDefinitionHash:z.string(),origin:z.enum(['required_suite','ad_hoc']),kind:z.literal('simulation'),outcome,complete:z.boolean(),stepsApplied:integer,attemptedStepCount:integer,fromObservationSeq:integer,toObservationSeq:integer,startAt:integer,endAt:integer,receipts:z.array(jsonSchema),assertions:z.array(jsonSchema),observations:z.array(jsonSchema),stopReason:z.string(),error:error.nullable(),resultHash:z.string(),expiresAt:integer,nextOffset:integer.nullable(),evidenceTruncated:z.boolean(),detailCounts:z.strictObject({assertions:integer,receipts:integer,observations:integer,total:integer}),oversizedDetails:z.array(z.strictObject({kind:z.enum(['assertion','receipt','observation']),index:integer,bytes:integer}))})])),requiredScopes:['simulation:read'],annotations:read}
];
export const manualSchema=z.strictObject({...mutationInput,operations:operationsSchema});
export const undoSchema=z.strictObject(mutationInput);
