# Base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# copy src
COPY . .

# install pnpm
RUN npm install -g pnpm

# install dependencies
RUN pnpm install

# build
RUN node build


#pull nginx as webser and load balancer
FROM nginx:stable-alpine3.20-slim

RUN apk update && apk upgrade --no-cache

# copy the build files to nginx entry point
COPY --from=0 /app/public /usr/share/nginx/html
