import {readFile, writeFile, mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
const require = createRequire(import.meta.url);
const expected = '105c3bed22d457e43e3d1c3c1c6959fda62a8fe06f0fc8a985303c3a2be72232';
const bytes = await readFile(require.resolve('@jitl/quickjs-wasmfile-release-sync/wasm'));
if(createHash('sha256').update(bytes).digest('hex') !== expected) throw new Error('Unexpected QuickJS WASM; update provenance only after re-verifying memory imports and limits.');
const module = await WebAssembly.compile(bytes);
const memories = WebAssembly.Module.imports(module).filter(item => item.kind === 'memory');
if(memories.length !== 1 || memories[0].module !== 'a' || memories[0].name !== 'a') throw new Error('Expected one imported memory.');
await mkdir(new URL('../src/shell/code/generated/', import.meta.url), {recursive: true});
await writeFile(new URL('../src/shell/code/generated/wasm.ts', import.meta.url), `// Generated by scripts/quickjs-assets.mjs from @jitl/quickjs-wasmfile-release-sync@0.32.0. MIT.\n// SHA256 ${expected}; one imported memory, supplied with initial=maximum=512 pages.\nexport default '${bytes.toString('base64')}';\n`);
console.log(`QuickJS ${bytes.length} bytes verified and embedded; SHA256 ${expected}`);
// Keep the actual ES2020 standard library in the compiler Worker, without DOM libs.
const tsPackage = JSON.parse(await readFile(require.resolve('typescript-browser/package.json'), 'utf8'));
if(tsPackage.version !== '6.0.3') throw new Error('Expected the pinned browser TypeScript compiler 6.0.3.');
const tsDirectory = new URL('.', `file://${require.resolve('typescript-browser/lib/lib.es2020.d.ts')}`);
const libraries = {};
async function includeLibrary(name) {
  const file = `lib.${name}.d.ts`;
  if(Object.hasOwn(libraries, `/${file}`)) return;
  if(!/^[a-z0-9.]+$/.test(name)) throw new Error('Unexpected TypeScript library path.');
  const source = await readFile(new URL(file, tsDirectory), 'utf8');
  libraries[`/${file}`] = source;
  for(const match of source.matchAll(/<reference lib="([^"]+)"/g)) await includeLibrary(match[1]);
}
await includeLibrary('es2020');
await writeFile(new URL('../src/shell/code/generated/standard-library.ts', import.meta.url), `// Generated from typescript@6.0.3 ES2020 standard libraries. Apache-2.0. No DOM libraries.\nexport default ${JSON.stringify(libraries)};\n`);
console.log(`Embedded ${Object.keys(libraries).length} TypeScript standard library declarations.`);
// The stock loader contains a dead fallback WASM URL that bundlers still emit.
// Preserve the exact loader except replacing that fallback with a required-provider error.
const enginePackage = new URL('.', `file://${require.resolve('@jitl/quickjs-wasmfile-release-sync/package.json')}`);
const loaderSource = await readFile(new URL('dist/emscripten-module.browser.mjs', enginePackage), 'utf8');
const loaderHash = '3b8e916b3248062be4bbd3281c8d2832f074e6850596fc9951e93b846139ddea';
if(createHash('sha256').update(loaderSource).digest('hex') !== loaderHash) throw new Error('Unexpected Emscripten loader source.');
const fallback = 'M??=c.locateFile?c.locateFile?c.locateFile("emscripten-module.wasm",u):u+"emscripten-module.wasm":(new URL("emscripten-module.wasm",import.meta.url)).href;return a((await ea(d)).instance)';
if(loaderSource.split(fallback).length !== 2) throw new Error('Emscripten fallback patch must match exactly once.');
const loader = loaderSource.replace(fallback, 'throw new Error("QuickJS requires an embedded module and fixed memory")');
await writeFile(new URL('../src/shell/code/generated/quickjs-loader.js', import.meta.url), `// Generated derivative of @jitl/quickjs-wasmfile-release-sync@0.32.0, MIT.\n// Original SHA256 ${loaderHash}; only the external WASM fallback is disabled.\n// oxlint-disable\n${loader}`);
await writeFile(new URL('../src/shell/code/generated/quickjs-loader.d.ts', import.meta.url), "import type {EmscriptenModuleLoader, QuickJSEmscriptenModule} from 'quickjs-emscripten-core';\ndeclare const load: EmscriptenModuleLoader<QuickJSEmscriptenModule>;\nexport default load;\n");
console.log('Generated fixed-provider browser loader; external WASM fallback removed.');
