const lang = {
  FilterIncludeExcludeInfo: 'Choose chats and types of chats that will\nappear and never appear in this folder.',
  FilterNameInputLabel: 'Folder Name',
  FilterMenuDelete: 'Delete Folder',
  FilterHeaderEdit: 'Edit Folder',
  FilterAllGroups: 'All Groups',
  FilterAllContacts: 'All Contacts',
  FilterAllNonContacts: 'All Non-Contacts',
  FilterAllChannels: 'All Channels',
  FilterAllBots: 'All Bots',
  FilterAllUnmuted: 'All Unmuted',
  FilterAllUnread: 'All Unread',
  FilterAllUnarchived: 'All Unarchived',
  WordDelimiter: ', ',
  WordDelimiterLast: ' and ',
  "EditProfile.FirstNameLabel": 'Name',
  "EditProfile.BioLabel": 'Bio (optional)',
  "EditProfile.Username.Label": 'Username (optional)',
  "EditProfile.Username.Available": 'Username is available',
  "EditProfile.Username.Taken": 'Username is already taken',
  "EditProfile.Username.Invalid": 'Username is invalid',
  "EditProfile.Username.Help": "You can choose a username on Telegram. If you do, people will be able to find you by this username and contact you without needing your phone number.\n\nYou can use a–z, 0–9 and underscores. Minimum length is 5 characters.",
  "ChatList.Menu.Archived": "Archived",
  Saved: "Saved",
  "General.Keyboard": "Keyboard",
  "General.SendShortcut.Enter": "Send by Enter",
  "General.SendShortcut.CtrlEnter": "Send by %s + Enter",
  "General.SendShortcut.NewLine.ShiftEnter": "New line by Shift + Enter",
  "General.SendShortcut.NewLine.Enter": "New line by Enter",
  "General.AutoplayMedia": "Auto-Play Media",
  "ChatBackground.UploadWallpaper": "Upload Wallpaper",
  "ChatBackground.SetColor": "Upload Wallpaper",
  "ChatBackground.Blur": "Upload Wallpaper",
  "Notifications.Sound": "Notification Sound",
  "Notifications.MessagePreview": "Message preview",
  "Checkbox.Enabled": "Enabled",
  "Checkbox.Disabled": "Disabled",
  "Privacy.Devices": {
    one_value: '%1$d device',
    other_value: '%1$d devices'
  },

  // * android
  FilterAlwaysShow: 'Include Chats',
  FilterNeverShow: 'Exclude Chats',
  FilterInclude: 'Included Chats',
  FilterExclude: 'Excluded Chats',
  FilterChatTypes: 'Chat types',
  FilterChats: 'Chats',
  FilterNew: 'New Folder',
  Filters: 'Folders',
  FilterRecommended: 'Recommended Folders',
  Add: 'Add',
  Chats: {
    one_value: '%1$d chat',
    other_value: '%1$d chats'
  },
  Channels: {
    one_value: '%1$d channel',
    other_value: '%1$d channels'
  },
  Groups: {
    one_value: '%1$d group',
    other_value: '%1$d groups'
  },
  Users: {
    one_value: "%1$d user",
    other_value: "%1$d users"
  },
  UsernameHelpLink: "This link opens a chat with you:\n%1$s",
  NewGroup: "New Group",
  Contacts: "Contacts",
  SavedMessages: "Saved Messages",
  Settings: "Settings",
  SettingsHelp: "Help",
  General: "General",
  TextSize: "Message Text Size",
  ChatBackground: "Chat Background",
  EnableAnimations: "Enable Animations",
  AutoDownloadMedia: "Auto-Download Media",
  AutodownloadContacts: 'Contacts',
  AutodownloadPrivateChats: 'Private Chats',
  AutodownloadGroupChats: 'Group Chats',
  AutodownloadChannels: 'Channels',
  AutoplayGIF: 'GIFs',
  AutoplayVideo: 'Videos',
  NotificationsForGroups: 'Notifications for groups',
  NotificationsForPrivateChats: 'Notifications for private chats',
  NotificationsForChannels: 'Notifications for channels',
  NotificationsPrivateChats: "Private Chats",
  NotificationsGroups: "Groups",
  NotificationsChannels: "Channels",
  NotificationsOther: 'Other',
  ContactJoined: 'Contact joined Telegram',
  Loading: "Loading...",
  Unblock: "Unblock",
  BlockedUsers: "Blocked Users",
  BlockedUsersInfo: 'Blocked users will not be able to contact you and will not see your Last Seen time.',
  BlockedEmpty: "None", 
  TwoStepVerification: "Two-Step Verification",
  PrivacyExceptions: "Exceptions",
  PrivacyLastSeen: "Last Seen & Online",
  PrivacySettings: "Privacy and Security",
  PrivacyTitle: "Privacy",
  PrivacyPhone: "Phone Number",
  PrivacyPhoneTitle: "Who can see my phone number?",
  PrivacyPhoneTitle2: "Who can find me by my number?",
  PrivacyPhoneInfo: "Users who have your number saved in their contacts will also see it on Telegram.",
  PrivacyPhoneInfo3: "Users who add your number to their contacts will see it on Telegram only if they are your contacts.",
  PrivacyProfilePhoto: "Profile Photos",
  PrivacyProfilePhotoTitle: "Who can see my profile photos & videos?",
  PrivacyP2PHeader: "Peer-to-Peer",
  PrivacyForwardsTitle: "Who can add a link to my account when forwarding my messages?",
  LastSeenTitle: "Who can see your Last Seen time?",
  SessionsTitle: "Active Sessions",
  CurrentSession: "This device",
  TerminateAllSessions: "Terminate All Other Sessions",
  TerminateSessionText: "Are you sure you want to terminate this session?",
  OtherSessions: "Active sessions",
  AreYouSureSessionTitle: "Terminate session",
  AreYouSureSessionsTitle: "Terminate sessions",
  AreYouSureSessions: "Are you sure you want to terminate all other sessions?",
  Terminate: "Terminate",
  WhoCanCallMe: "Who can call me?",
  WhoCanAddMe: "Who can add me to group chats?",
  ArchivedChats: "Archived Chats",
  Cancel: "Cancel",

  // * macos
  "ChatList.Filter.Header": "Create folders for different groups of chats and quickly switch between them.",
  "ChatList.Filter.NewTitle": "Create Folder",
  "ChatList.Filter.List.Title": "Chat Folders",
  "ChatList.Filter.Include.AddChat": "Add Chats",
  "ChatList.Filter.Exclude.AddChat": "Add Chats",
  "ChatList.Filter.All": "All",
  "ChatList.Filter.Contacts": "Contacts",
  "ChatList.Filter.NonContacts": "Non-Contacts",
  "ChatList.Filter.Groups": "Groups",
  "ChatList.Filter.Channels": "Channels",
  "ChatList.Filter.Bots": "Bots",
  "ChatList.Filter.MutedChats": "Muted",
  "ChatList.Filter.ReadChats": "Read",
  "ChatList.Filter.Archive": "Archived",
  "Bio.Description": "Any details such as age, occupation or city.\nExample: 23 y.o. designer from San Francisco",
  "EditAccount.Username": "Username",
  "EditAccount.Title": "Edit Profile",
  "EditAccount.Logout": "Log Out",
  "Login.Register.LastName.Placeholder": "Last Name",
  "AccountSettings.Filters": "Chat Folders",
  "AccountSettings.Notifications": "Notifications and Sounds",
  "AccountSettings.PrivacyAndSecurity": "Privacy and Security",
  "AccountSettings.Language": "Language",
  "Telegram.GeneralSettingsViewController": "General Settings",
  "Telegram.InstalledStickerPacksController": "Stickers",
  "Telegram.NotificationSettingsViewController": "Notifications",
  "Stickers.SuggestStickers": "Suggest Stickers by Emoji",
  "InstalledStickers.LoopAnimated": "Loop Animated Stickers",
  "PrivacyAndSecurity.Item.On": "On",
  "PrivacyAndSecurity.Item.Off": "Off",
  "PrivacySettings.VoiceCalls": "Calls",
  "PrivacySettings.Forwards": "Forwarded Messages",
  "PrivacySettings.Groups": "Groups and Channels",
  "PrivacySettingsController.AddUsers": "Add Users",
  "PrivacySettingsController.GroupDescription": "You can restrict who can add you to groups and channels with granular precision.",
  "PrivacySettingsController.Forwards.CustomHelp": "You can restrict who can add a link to your account when forwarding your messages.",
  "PrivacySettingsController.P2p.Desc": "Disabling peer-to-peer will relay all calls through Telegram servers to avoid revealing your IP address, but may slightly decrease audio and video quality.",
  "PrivacySettingsController.PhoneCallDescription": "You can restrict who can call you with granular precision.",
  "PrivacySettingsController.ProfilePhoto.CustomHelp": "You can restrict who can see your profile photo with granular precision.",
  "PrivacySettingsController.LastSeenDescription": "You won't see Last Seen and Online statuses for people with whom you don't share yours. Approximate last seen will be shown instead (recently, within a week, within a month).",
  "PrivacySettingsController.PeerInfo": "You can add users or entire groups as exceptions that will override the settings above.",
  "PrivacySettingsController.Everbody": "Everybody",
  "PrivacySettingsController.MyContacts": "My Contacts",
  "PrivacySettingsController.Nobody": "Nobody",
  "PrivacySettingsController.NeverShare": "Never Share With",
  "PrivacySettingsController.AlwaysShare": "Always Share With",
  "PrivacySettingsController.NeverAllow": "Never Allow",
  "PrivacySettingsController.AlwaysAllow": "Always Allow",
  "PrivacySettingsController.UserCount": {
    one_value: '%d user',
    other_value: '%d users'
  },
  "RecentSessions.Error.FreshReset": "For security reasons, you can't terminate older sessions from a device that you've just connected. Please use an earlier connection or wait for a few hours.",
};

export default lang;
