const lang = {
  'Login.Title': 'Sign in to Telegram',
  'Login.PhoneLabel': 'Phone Number',
  'Login.PhoneLabelInvalid': 'Phone Number Invalid',
  'Login.StartText': 'Please confirm your country code\nand enter your phone number.',
  'Login.Code.SentSms': 'We have sent you an SMS\nwith the code.',
  'Login.Code.SentInApp': 'We have sent you a message in Telegram\nwith the code.',
  'Login.Code.SentCall': 'We will call you and dictate\nthe code.',
  'Login.Code.SentEmail': 'Please check your email **%s** (don\'t forget the spam folder) and enter the code we just sent you.',
  'Login.Code.SentUnknown': 'Please check everything\nfor a code (type: %s)',
  'Login.Code.SentMissedCall': 'Within the next few seconds you should receive\na short call from **%s**. Don\'t answer it —\njust enter the last digits of that number.',
  'Login.Code.SentSmsWord': 'We\'ve sent an SMS with a secret word\nto your phone **%s**.',
  'Login.Code.SentSmsWordBeginning': 'We\'ve sent an SMS with a secret word that starts\nwith "**%2$s**" to your phone **%1$s**.',
  'Login.Code.SentSmsPhrase': 'We\'ve sent an SMS with a secret phrase\nto your phone **%s**.',
  'Login.Code.SentSmsPhraseBeginning': 'We\'ve sent an SMS with a secret phrase that starts\nwith "**%2$s**" to your phone **%1$s**.',
  'Login.Code.SecretWord': 'Secret word',
  'Login.Code.SecretPhrase': 'Secret phrase',
  'Login.Code.WordInvalid': 'Incorrect, please try again',
  'Login.Code.WordBeginningInvalid': 'Incorrect word',
  'Login.Code.SmsAvailableIn': 'You can request an SMS in %s',
  'Login.Code.CallAvailableIn': 'You can request a call in %s',
  'Login.Code.ResendSms': '[Send the code as an SMS]()',
  'Login.Code.ResendCall': '[Get the code via a phone call]()',
  'Login.Code.ResendFragment': '[Get a code via Fragment]()',
  'Login.Code.Resending': 'Requesting a new code...',
  'Login.EditPhone': 'Edit phone number',
  'Login.EditEmail': 'Change email address',
  'Login.Password.Title': 'Enter Your Password',
  'Login.Password.Subtitle': 'Your account is protected with\nan additional password',
  'Login.Register.Subtitle': 'Enter your name and add\na profile photo',
  'PleaseWait': 'Please wait...',

  'ForgotPassword': '[Forgot Password?]()',
  'TroubleEmail': '[Can\'t access this email?]()',
  'Login.ResetPassword.Title': 'Reset Password',
  'Login.ResetPassword.Subtitle': 'Enter the code we just sent\nto your email **%s**.',
  'Login.ResetPassword.Cancel': 'Cancel',
  'Login.ResetPassword.NoEmailText': 'Since you didn\'t provide a recovery email when setting up your password, your remaining options are either to remember your password or to reset your account.',
  'Login.ResetPassword.TroubleEmailText': 'If you can\'t restore access to your email, your remaining options are either to remember your password or to reset your account.',
  'Login.ResetPassword.ResetAccount': 'Reset Account',
  'Login.ResetAccount.Title': 'Warning',
  'Login.ResetAccount.Text': 'This action can\'t be undone.\n\nIf you reset your account, all your messages and chats will be deleted.',
  'Login.ResetAccountFail.Title': 'Sorry',
  'Login.ResetAccountFail.TextCancelled': 'Your recent attempts to reset this account have been cancelled by its active user. Please try again in 7 days.',
  'Login.ResetAccountFail.TextWait': 'Since this account is active and protected by a password, we will delete it in 1 week for security purposes.\n\nYou can cancel this process at any time.\n\nYou\'ll be able to reset your account in: %s.',
  'Login.ResetEmail.Title': 'Reset Email',
  'Login.ResetEmail.Text': 'You can change your login email if you are logged into Telegram from another device.\n\nOtherwise, if you don\'t have access to this email, you can reset it with an **SMS** code in **%s**.',
  'Login.ResetEmail.Pending': 'Email will be reset in %s. [Reset now via SMS]()',
  'Login.ResetEmail.PleaseWait': 'Resetting email, please wait...',
  'Login.ResetEmail.NeedPremium': 'Telegram Premium Required',
  'Login.ResetEmail.NeedPremiumText': 'Due to the high cost of SMS in your country, you need a **Telegram Premium** account to immediately reset this email via an SMS code.\n\nYou can ask a friend to gift a Premium subscription for your account',
  'Login.Passkey': 'Log in by passkey >',
  'Login.Passkey.Error': 'Something went wrong',
  'Login.Passkey.Error.NotFound': 'Used passkey is not tied to any account',

  // * android
  'Code': 'Code',
  'LoginPassword': 'Password',
  'YourName': 'Your Name',
  'FirstName': 'First name (required)',
  'LastName': 'Last name (optional)',
  'StartMessaging': 'Start Messaging',
  'Country': 'Country',

  // * macos
  'Contacts.PhoneNumber.Placeholder': 'Phone Number',
  'Login.Next': 'Next',
  'Login.ContinueOnLanguage': 'Continue in English',
  'Login.QR.Title': 'Log in by QR Code',
  'Login.QR.Help1': 'Open Telegram on your phone',
  'Login.QR.Help2': 'Go to **Settings** > **Devices** > **Add Device**',
  'Login.QR.Help3': 'Point your phone at this screen to confirm login',
  'Login.QR.Cancel': 'Log in by phone number >',
  'Login.QR.Login': 'Log in by QR Code >',
  'Login.QR.Subtitle': 'Scan with Telegram app on your phone',
  // the link target stays empty on purpose: tweb's formatter takes the anchor from the arguments
  // for `[]()`, while a `%1$@` inside the target makes it start looking at argument 1 and crash
  // on the missing one (the macOS string this came from substitutes the url into the target)
  'PhoneNumber.Code.Fragment.Info': 'Get the code in the Numbers section on [Fragment]()',
  'PHONE_CODE_INVALID': 'Invalid code',
  'PHONE_CODE_EXPIRED': 'Code expired',
  'PASSWORD_HASH_INVALID': 'Incorrect password'
};

export default lang;
