const lang = {
  "AttachAlbum": "Album",
  "BlockModal.Search.Placeholder": "Block user...",
  "FilterIncludeExcludeInfo": "Choose chats and types of chats that will\nappear and never appear in this folder.",
  "FilterNameInputLabel": "Folder Name",
  "FilterMenuDelete": "Delete Folder",
  "FilterHeaderEdit": "Edit Folder",
  "FilterAllGroups": "All Groups",
  "FilterAllContacts": "All Contacts",
  "FilterAllNonContacts": "All Non-Contacts",
  "FilterAllChannels": "All Channels",
  "FilterAllBots": "All Bots",
  "WordDelimiter": ", ",
  "WordDelimiterLast": " and ",
  "EditProfile.FirstNameLabel": "Name",
  "EditProfile.BioLabel": "Bio (optional)",
  "EditProfile.Username.Label": "Username (optional)",
  "EditProfile.Username.Available": "Username is available",
  "EditProfile.Username.Taken": "Username is already taken",
  "EditProfile.Username.Invalid": "Username is invalid",
  "EditProfile.Username.Help": "You can choose a username on Telegram. If you do, people will be able to find you by this username and contact you without needing your phone number.\n\nYou can use a–z, 0–9 and underscores. Minimum length is 5 characters.",
  "ExceptionModal.Search.Placeholder": "Add exception...",
  "ChatList.Menu.Archived": "Archived",
  "Chat.Menu.SelectMessages": "Select Messages",
  "Chat.Menu.ClearSelection": "Clear Selection",
  "Chat.Input.UnpinAll": "Unpin All Messages",
  "Chat.Input.Attach.PhotoOrVideo": "Photo or Video",
  "Chat.Input.Attach.Document": "Document",
  "Chat.Subscribe": "SUBSCRIBE",
  "Chat.Selection.MessagesCount": {
    "one_value": "%d Message",
    "other_value": "%d Messages"
  },
  "Chat.Selection.LimitToast": "Max selection count reached.",
  "Saved": "Saved",
  "General.Keyboard": "Keyboard",
  "General.SendShortcut.Enter": "Send by Enter",
  "General.SendShortcut.CtrlEnter": "Send by %s + Enter",
  "General.SendShortcut.NewLine.ShiftEnter": "New line by Shift + Enter",
  "General.SendShortcut.NewLine.Enter": "New line by Enter",
  "General.AutoplayMedia": "Auto-Play Media",
  "ChatBackground.UploadWallpaper": "Upload Wallpaper",
  "ChatBackground.SetColor": "Set a Color",
  "ChatBackground.Blur": "Blur Wallpaper Image",
  "Notifications.Sound": "Notification Sound",
  "Notifications.MessagePreview": "Message preview",
  "NewPrivateChat": "New Private Chat",
  "NewPoll.OptionLabel": "Option %d",
  "NewPoll.Create": "CREATE",
  "Message.Context.Selection.Copy": "Copy selected",
  "Message.Context.Selection.Clear": "Clear selection",
  "Message.Context.Selection.Delete": "Delete selected",
  "Message.Context.Selection.Forward": "Forward selected",
  "Message.Context.Selection.SendNow": "Send Now selected",
  "Checkbox.Enabled": "Enabled",
  "Checkbox.Disabled": "Disabled",
  "Error.PreviewSender.CaptionTooLong": "Caption is too long.",
  "PreviewSender.GroupItems": "Group items",
  "PreviewSender.Send": "SEND",
  "PreviewSender.SendAlbum": {
    "one_value": "Send Album",
    "other_value": "Send %d Albums"
  },
  "Privacy.Devices": {
    "one_value": "%1$d device",
    "other_value": "%1$d devices"
  },
  "PrivacyModal.Search.Placeholder": "Add Users or Groups...",

  // * android
  "ActionCreateChannel": "Channel created",
  "ActionCreateGroup": "un1 created the group",
  "ActionChangedTitle": "un1 changed the group name to un2",
  "ActionRemovedPhoto": "un1 removed the group photo",
  "ActionChangedPhoto": "un1 changed the group photo",
  "ActionChangedVideo": "un1 changed the group video",
  "ActionAddUser": "un1 added un2",
  "ActionAddUserSelf": "un1 returned to the group",
  "ActionAddUserSelfYou": "You returned to the group",
  "ActionAddUserSelfMega": "un1 joined the group",
  "ActionLeftUser": "un1 left the group",
  "ActionKickUser": "un1 removed un2",
  "ActionInviteUser": "un1 joined the group via invite link",
  "ActionPinnedNoText": "un1 pinned a message",
  "ActionMigrateFromGroup": "This group was upgraded to a supergroup",
  "AttachPhoto": "Photo",
  "AttachVideo": "Video",
  "AttachGif": "GIF",
  "AttachLocation": "Location",
  "AttachLiveLocation": "Live Location",
  "AttachContact": "Contact",
  "AttachDocument": "File",
  "AttachSticker": "Sticker",
  "AttachAudio": "Voice message",
  "AttachRound": "Video message",
  "AttachGame": "Game",
  //"ChannelJoined": "You joined this channel",
  "ChannelMegaJoined": "You joined this group",
  "Channel.DescriptionPlaceholder": "Description (optional)",
  "Draft": "Draft",
  "FilterAlwaysShow": "Include Chats",
  "FilterNeverShow": "Exclude Chats",
  "FilterInclude": "Included Chats",
  "FilterExclude": "Excluded Chats",
  "FilterChatTypes": "Chat types",
  "FilterChats": "Chats",
  "FilterNew": "New Folder",
  "Filters": "Folders",
  "FilterRecommended": "Recommended Folders",
  "FilterShowMoreChats": {
    "one_value": "Show %1$d More Chat",
    "other_value": "Show %1$d More Chats"
  },
  "FromYou": "You",
  "Add": "Add",
  "Chats": {
    "one_value": "%1$d chat",
    "other_value": "%1$d chats"
  },
  "Channels": {
    "one_value": "%1$d channel",
    "other_value": "%1$d channels"
  },
  "Groups": {
    "one_value": "%1$d group",
    "other_value": "%1$d groups"
  },
  "Users": {
    "one_value": "%1$d user",
    "other_value": "%1$d users"
  },
  "Members": {
    "one_value": "%1$d member",
    "other_value": "%1$d members"
  },
  "UsernameHelpLink": "This link opens a chat with you:\n%1$s",
  "NewChannel": "New Channel",
  "NewGroup": "New Group",
  "Contacts": "Contacts",
  "SavedMessages": "Saved Messages",
  "Settings": "Settings",
  "SettingsHelp": "Help",
  "General": "General",
  "TextSize": "Message Text Size",
  "ChatBackground": "Chat Background",
  "EnableAnimations": "Enable Animations",
  "AutoDownloadMedia": "Auto-Download Media",
  "AutodownloadContacts": "Contacts",
  "AutodownloadPrivateChats": "Private Chats",
  "AutodownloadGroupChats": "Group Chats",
  "AutodownloadChannels": "Channels",
  "AutoplayGIF": "GIFs",
  "AutoplayVideo": "Videos",
  "NotificationsForGroups": "Notifications for groups",
  "NotificationsForPrivateChats": "Notifications for private chats",
  "NotificationsForChannels": "Notifications for channels",
  "NotificationsPrivateChats": "Private Chats",
  "NotificationsGroups": "Groups",
  "NotificationsChannels": "Channels",
  "NotificationsOther": "Other",
  "MarkAsUnread": "Mark as unread",
  "MarkAsRead": "Mark as read",
  "ContactJoined": "Contact joined Telegram",
  "Loading": "Loading...",
  "Unblock": "Unblock",
  "BlockedUsers": "Blocked Users",
  "BlockedUsersInfo": "Blocked users will not be able to contact you and will not see your Last Seen time.",
  "BlockedEmpty": "None", 
  "TwoStepVerification": "Two-Step Verification",
  "PinnedMessage": "Pinned Message",
  "PinnedMessagesCount": {
    "one_value": "Pinned Message",
    "other_value": "%1$d Pinned Messages"
  },
  //"PreviousPinnedMessage": "Previous Message",
  "PrivacyExceptions": "Exceptions",
  "PrivacyLastSeen": "Last Seen & Online",
  "PrivacySettings": "Privacy and Security",
  "PrivacyTitle": "Privacy",
  "PrivacyPhone": "Phone Number",
  "PrivacyPhoneTitle": "Who can see my phone number?",
  "PrivacyPhoneTitle2": "Who can find me by my number?",
  "PrivacyPhoneInfo": "Users who have your number saved in their contacts will also see it on Telegram.",
  "PrivacyPhoneInfo3": "Users who add your number to their contacts will see it on Telegram only if they are your contacts.",
  "PrivacyProfilePhoto": "Profile Photos",
  "PrivacyProfilePhotoTitle": "Who can see my profile photos & videos?",
  "PrivacyP2PHeader": "Peer-to-Peer",
  "PrivacyForwardsTitle": "Who can add a link to my account when forwarding my messages?",
  "Reminders": "Reminders",
  "ScheduledMessages": "Scheduled Messages",
  "LastSeenTitle": "Who can see your Last Seen time?",
  "SessionsTitle": "Active Sessions",
  "CurrentSession": "This device",
  "TerminateAllSessions": "Terminate All Other Sessions",
  "TerminateSessionText": "Are you sure you want to terminate this session?",
  "OtherSessions": "Active sessions",
  "AreYouSureSessionTitle": "Terminate session",
  "AreYouSureSessionsTitle": "Terminate sessions",
  "AreYouSureSessions": "Are you sure you want to terminate all other sessions?",
  "Terminate": "Terminate",
  "WhoCanCallMe": "Who can call me?",
  "WhoCanAddMe": "Who can add me to group chats?",
  "ArchivedChats": "Archived Chats",
  "Cancel": "Cancel",
  "HistoryCleared": "History was cleared",
  "Archive": "Archive",
  "Unarchive": "Unarchive",
  "Delete": "Delete",
  "Reply": "Reply",
  "Edit": "Edit",
  "Forward": "Forward",
  "CopyLink": "Copy Link",
  "Copy": "Copy",
  "Search": "Search",
  "LinkCopied": "Link copied to clipboard",
  "LinkCopiedPrivateInfo": "This link will only work for members of this chat.",
  "GroupAddMembers": "Add Members",
  "SendMessageTo": "Add people...",
  "SelectChat": "Select Chat",
  "JumpToDate": "Jump to Date",
  "Caption": "Caption",
  "Message": "Message",
  "Poll": "Poll",
  "SharedFilesTab2": "Files",
  "SharedMediaTab2": "Media",
  //"SharedMediaTabFull2": "Shared Media",
  //"SharedGroupsTab2": "Groups",
  "SharedLinksTab2": "Links",
  "SharedMusicTab2": "Music",
  "SharedVoiceTab2": "Voice",
  //"SharedGIFsTab2": "GIFs",
  "NewPoll": "New Poll",
  "PollOptions": "Poll options",
  "AskAQuestion": "Ask a Question",
  "AddAnExplanationInfo": "Users will see this text after choosing the wrong answer, good for educational purposes.",
  "AccDescrQuizExplanation": "Explanation",

  // * macos
  "AccountSettings.Filters": "Chat Folders",
  "AccountSettings.Notifications": "Notifications and Sounds",
  "AccountSettings.PrivacyAndSecurity": "Privacy and Security",
  "AccountSettings.Language": "Language",
  "Bio.Description": "Any details such as age, occupation or city.\nExample: 23 y.o. designer from San Francisco",
  "Chat.CopySelectedText": "Copy Selected Text",
  "Chat.Date.ScheduledFor": "Scheduled for %@",
  //"Chat.Date.ScheduledUntilOnline": "Scheduled until online",
  "Chat.Date.ScheduledForToday": "Scheduled for today",
  "Chat.Service.PeerJoinedTelegram": "%@ joined Telegram",
  "Chat.Service.Channel.UpdatedTitle": "Channel renamed to \"%@\"",
  "Chat.Service.Channel.UpdatedPhoto": "Channel photo updated",
  "Chat.Service.Channel.RemovedPhoto": "Channel photo removed",
  "Chat.Service.Channel.UpdatedVideo": "Channel video updated",
  "Chat.Service.BotPermissionAllowed": "You allowed this bot to message you when you logged in on %@",
  "Chat.Poll.Unvote": "Retract Vote",
  "Chat.Poll.Stop": "Stop Poll",
  // "Chat.Poll.Stop.Confirm.Header": "Stop Poll?",
  // "Chat.Poll.Stop.Confirm.Text": "If you stop this poll now, nobody will be able to vote in it anymore. This action cannot be undone.",
  // "Chat.Pinned.UnpinAll": {
  //   "one_value": "Unpin %d Message",
  //   "other_value": "Unpin All %d Messages"
  // },
  "Chat.Pinned.DontShow": "Don't Show Pinned Messages",
  "Chat.Title.Comments": {
    "one_value": "%d Comment",
    "other_value": "%d Comments"
  },
  "Chat.Send.WithoutSound": "Send Without Sound",
  "Chat.Send.SetReminder": "Set a Reminder",
  "Chat.Send.ScheduledMessage": "Schedule Message",
  "ChatList.Context.Mute": "Mute",
  "ChatList.Context.Unmute": "Unmute",
  "ChatList.Context.Pin": "Pin",
  "ChatList.Context.Unpin": "Unpin",
  "ChatList.Service.Call.incoming": "Incoming Call (%@)",
  "ChatList.Service.Call.outgoing": "Outgoing Call (%@)",
  "ChatList.Service.Call.Cancelled": "Cancelled Call",
  "ChatList.Service.Call.Missed": "Missed Call",
  "ChatList.Filter.Header": "Create folders for different groups of chats and quickly switch between them.",
  "ChatList.Filter.NewTitle": "Create Folder",
  "ChatList.Filter.List.Title": "Chat Folders",
  "ChatList.Filter.Include.AddChat": "Add Chats",
  "ChatList.Filter.Exclude.AddChat": "Add Chats",
  "ChatList.Filter.All": "All",
  "ChatList.Filter.Contacts": "Contacts",
  "ChatList.Filter.NonContacts": "Non-Contacts",
  "ChatList.Filter.Groups": "Groups",
  "ChatList.Filter.Channels": "Channels",
  "ChatList.Filter.Bots": "Bots",
  "ChatList.Filter.MutedChats": "Muted",
  "ChatList.Filter.ReadChats": "Read",
  "ChatList.Filter.Archive": "Archived",
  "Channel.ChannelNameHolder": "Channel Name",
  "Channel.DescriptionHolderDescrpiton": "You can provide an optional description for your channel.",
  "CreateGroup.NameHolder": "Group Name",
  "Date.Today": "Today",
  "EditAccount.Username": "Username",
  "EditAccount.Title": "Edit Profile",
  "EditAccount.Logout": "Log Out",
  "Login.Register.LastName.Placeholder": "Last Name",
  "Telegram.GeneralSettingsViewController": "General Settings",
  "Telegram.InstalledStickerPacksController": "Stickers",
  "Telegram.NotificationSettingsViewController": "Notifications",
  "Stickers.SuggestStickers": "Suggest Stickers by Emoji",
  "ShareModal.Search.ForwardPlaceholder": "Forward to...",
  "InstalledStickers.LoopAnimated": "Loop Animated Stickers",
  "PreviewSender.CaptionPlaceholder": "Add a caption...",
  "PreviewSender.SendFile": {
    "one_value": "Send File",
    "other_value": "Send %d Files"
  },
  "PreviewSender.SendPhoto": {
    "one_value": "Send Photo",
    "other_value": "Send %d Photos"
  },
  "PreviewSender.SendVideo": {
    "one_value": "Send Video",
    "other_value": "Send %d Videos"
  },
  "PrivacyAndSecurity.Item.On": "On",
  "PrivacyAndSecurity.Item.Off": "Off",
  "PrivacySettings.VoiceCalls": "Calls",
  "PrivacySettings.Forwards": "Forwarded Messages",
  "PrivacySettings.Groups": "Groups and Channels",
  "PrivacySettingsController.AddUsers": "Add Users",
  "PrivacySettingsController.GroupDescription": "You can restrict who can add you to groups and channels with granular precision.",
  "PrivacySettingsController.Forwards.CustomHelp": "You can restrict who can add a link to your account when forwarding your messages.",
  "PrivacySettingsController.P2p.Desc": "Disabling peer-to-peer will relay all calls through Telegram servers to avoid revealing your IP address, but may slightly decrease audio and video quality.",
  "PrivacySettingsController.PhoneCallDescription": "You can restrict who can call you with granular precision.",
  "PrivacySettingsController.ProfilePhoto.CustomHelp": "You can restrict who can see your profile photo with granular precision.",
  "PrivacySettingsController.LastSeenDescription": "You won't see Last Seen and Online statuses for people with whom you don't share yours. Approximate last seen will be shown instead (recently, within a week, within a month).",
  "PrivacySettingsController.PeerInfo": "You can add users or entire groups as exceptions that will override the settings above.",
  "PrivacySettingsController.Everbody": "Everybody",
  "PrivacySettingsController.MyContacts": "My Contacts",
  "PrivacySettingsController.Nobody": "Nobody",
  "PrivacySettingsController.NeverShare": "Never Share With",
  "PrivacySettingsController.AlwaysShare": "Always Share With",
  "PrivacySettingsController.NeverAllow": "Never Allow",
  "PrivacySettingsController.AlwaysAllow": "Always Allow",
  "PrivacySettingsController.UserCount": {
    "one_value": "%d user",
    "other_value": "%d users"
  },
  "RecentSessions.Error.FreshReset": "For security reasons, you can't terminate older sessions from a device that you've just connected. Please use an earlier connection or wait for a few hours.",
  "Message.Context.Select": "Select",
  "Message.Context.Pin": "Pin",
  "Message.Context.Unpin": "Unpin",
  "NewPoll.Anonymous": "Anonymous Voting",
  "NewPoll.Explanation.Placeholder": "Add a Comment (Optional)",
  "NewPoll.OptionsAddOption": "Add an Option",
  "NewPoll.MultipleChoice": "Multiple Answers",
  "NewPoll.Quiz": "Quiz Mode"
};

export default lang;
