const lang = {
  FilterIncludeExcludeInfo: 'Choose chats and types of chats that will\nappear and never appear in this folder.',
  FilterNameInputLabel: 'Folder Name',
  FilterMenuDelete: 'Delete Folder',
  FilterHeaderEdit: 'Edit Folder',
  FilterAllGroups: 'All Groups',
  FilterAllContacts: 'All Contacts',
  FilterAllNonContacts: 'All Non-Contacts',
  FilterAllChannels: 'All Channels',
  FilterAllBots: 'All Bots',
  FilterAllUnmuted: 'All Unmuted',
  FilterAllUnread: 'All Unread',
  FilterAllUnarchived: 'All Unarchived',
  WordDelimiter: ', ',
  WordDelimiterLast: ' and ',
  "EditProfile.FirstNameLabel": 'Name',
  "EditProfile.BioLabel": 'Bio (optional)',
  "EditProfile.Username.Label": 'Username (optional)',
  "EditProfile.Username.Available": 'Username is available',
  "EditProfile.Username.Taken": 'Username is already taken',
  "EditProfile.Username.Invalid": 'Username is invalid',
  "EditProfile.Username.Help": "You can choose a username on Telegram. If you do, people will be able to find you by this username and contact you without needing your phone number.\n\nYou can use a–z, 0–9 and underscores. Minimum length is 5 characters.",
  "ChatList.Menu.Archived": "Archived",
  Saved: "Saved",
  "General.Keyboard": "Keyboard",
  "General.SendShortcut.Enter": "Send by Enter",
  "General.SendShortcut.CtrlEnter": "Send by %s + Enter",
  "General.SendShortcut.NewLine.ShiftEnter": "New line by Shift + Enter",
  "General.SendShortcut.NewLine.Enter": "New line by Enter",
  "General.AutoplayMedia": "Auto-Play Media",
  "ChatBackground.UploadWallpaper": "Upload Wallpaper",
  "ChatBackground.SetColor": "Upload Wallpaper",
  "ChatBackground.Blur": "Upload Wallpaper",
  "Notifications.Sound": "Notification Sound",
  "Notifications.MessagePreview": "Message preview",
  "Checkbox.Enabled": "Enabled",
  "Checkbox.Disabled": "Disabled",
  "Privacy.Devices": {
    one_value: '%1$d device',
    other_value: '%1$d devices'
  },
  "Privacy.BlockedUsers": {
    one_value: '%1$d user',
    other_value: '%1$d users',
  },
  "Privacy.BlockedUsers.None": 'None',

  // * android
  FilterAlwaysShow: 'Include Chats',
  FilterNeverShow: 'Exclude Chats',
  FilterInclude: 'Included Chats',
  FilterExclude: 'Excluded Chats',
  FilterChatTypes: 'Chat types',
  FilterChats: 'Chats',
  FilterNew: 'New Folder',
  Filters: 'Folders',
  FilterRecommended: 'Recommended Folders',
  Add: 'Add',
  Chats: {
    one_value: '%1$d chat',
    other_value: '%1$d chats'
  },
  Channels: {
    one_value: '%1$d channel',
    other_value: '%1$d channels'
  },
  Groups: {
    one_value: '%1$d group',
    other_value: '%1$d groups'
  },
  UsernameHelpLink: "This link opens a chat with you:\n%1$s",
  NewGroup: "New Group",
  Contacts: "Contacts",
  SavedMessages: "Saved Messages",
  Settings: "Settings",
  SettingsHelp: "Help",
  General: "General",
  TextSize: "Message Text Size",
  ChatBackground: "Chat Background",
  EnableAnimations: "Enable Animations",
  AutoDownloadMedia: "Auto-Download Media",
  AutodownloadContacts: 'Contacts',
  AutodownloadPrivateChats: 'Private Chats',
  AutodownloadGroupChats: 'Group Chats',
  AutodownloadChannels: 'Channels',
  AutoplayGIF: 'GIFs',
  AutoplayVideo: 'Videos',
  NotificationsForGroups: 'Notifications for groups',
  NotificationsForPrivateChats: 'Notifications for private chats',
  NotificationsForChannels: 'Notifications for channels',
  NotificationsOther: 'Other',
  ContactJoined: 'Contact joined Telegram',
  Loading: "Loading...",
  BlockedUsers: "Blocked Users",
  TwoStepVerification: "Two-Step Verification",
  PrivacySettings: "Privacy and Security",
  PrivacyTitle: "Privacy",
  PrivacyPhoneTitle: "Who can see my phone number?",
  PrivacyProfilePhotoTitle: "Who can see my profile photos & videos?",
  PrivacyForwardsTitle: "Who can add a link to my account when forwarding my messages?",
  LastSeenTitle: "Who can see your Last Seen time?",
  SessionsTitle: "Active Sessions",
  WhoCanCallMe: "Who can call me?",
  WhoCanAddMe: "Who can add me to group chats?",

  // * macos
  "ChatList.Filter.Header": "Create folders for different groups of chats and quickly switch between them.",
  "ChatList.Filter.NewTitle": "Create Folder",
  "ChatList.Filter.List.Title": "Chat Folders",
  "ChatList.Filter.Include.AddChat": "Add Chats",
  "ChatList.Filter.Exclude.AddChat": "Add Chats",
  "ChatList.Filter.All": "All",
  "ChatList.Filter.Contacts": "Contacts",
  "ChatList.Filter.NonContacts": "Non-Contacts",
  "ChatList.Filter.Groups": "Groups",
  "ChatList.Filter.Channels": "Channels",
  "ChatList.Filter.Bots": "Bots",
  "ChatList.Filter.MutedChats": "Muted",
  "ChatList.Filter.ReadChats": "Read",
  "ChatList.Filter.Archive": "Archived",
  "Bio.Description": "Any details such as age, occupation or city.\nExample: 23 y.o. designer from San Francisco",
  "EditAccount.Username": "Username",
  "EditAccount.Title": "Edit Profile",
  "EditAccount.Logout": "Log Out",
  "Login.Register.LastName.Placeholder": "Last Name",
  "AccountSettings.Filters": "Chat Folders",
  "AccountSettings.Notifications": "Notifications and Sounds",
  "AccountSettings.PrivacyAndSecurity": "Privacy and Security",
  "AccountSettings.Language": "Language",
  "Telegram.GeneralSettingsViewController": "General Settings",
  "Telegram.InstalledStickerPacksController": "Stickers",
  "Telegram.NotificationSettingsViewController": "Notifications",
  "Stickers.SuggestStickers": "Suggest Stickers by Emoji",
  "InstalledStickers.LoopAnimated": "Loop Animated Stickers",
  "AutoDownloadSettings.TypePrivateChats": "Private Chats",
  "AutoDownloadSettings.TypeGroupChats": "Groups",
  "AutoDownloadSettings.TypeChannels": "Channels",
};

export default lang;
